resources:
  - name: bash
    type: gitRepo
    repoPath: vijayreddy1991/bash
    configuration:
      integrationName: vijayku_github
      branches:
        only: master
    version:
      sha: master

pipelines:
  - name: pipeline1234
    steps:
      - name: testbash1
        type: bash
        configuration:
          affinityGroup: vijay
#           priority: 3
          nodePool: kermit_ubuntu_pool
          chronological: true     
        setup:
#           environmentVariables:
#             normal:
#               vijay: kumar  
          runtime:            
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
              custom:
                name: node
                tag: latest
                options: ""
        requires:                  
          integrations:
            - vijaydocker
       
        triggeredBy:
          resources:
            - bash
        execution:
          onStart:
            - printenv
          onExecute:
#             - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
            - java -version

      - name: testbash2
        type: bash
        configuration:
          affinityGroup: vijay
#           priority: 2
#           timeoutSeconds: <job timeout limit>
          nodePool: kermit_ubuntu_pool
#           chronological: false
        setup:
#           environmentVariables:
#             normal:
#               ENV1: value1
#               ENV2: value2
#             encrypted:
#               SECURE_ENV1: <encrypted secure>
#               SECURE_ENV2: <encrypted secure>
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          steps:
            - testbash1
        execution:
          onStart:
            - printenv
          onExecute:
#             - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
#           onSuccess:
#               - printenv
#           onFailure:
#            - printenv
#           onComplete: #always
#             - test "$vijay" == "kumar"
#             - printenv
#           onCancel:
#             - test "$ENV1" == "value1"
            

      - name: testbash3
        type: bash
        configuration:
          affinityGroup: kumar
#           priority: 1
#           timeoutSeconds: <job timeout limit>
          nodePool: kermit_ubuntu_pool
#           chronological: false        
        setup:
#           environmentVariables:
#             normal:
#               vijay: kumar  
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 8.16.0
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          steps:
            - testbash2
        execution:
          onStart:
            - printenv
          onExecute:
#             - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
#           onSuccess:
#             - test "$ENV1" == "value1"
#               - printenv
#           onFailure:
#            - printenv
#           onComplete: #always
# #             - test "$vijay" == "kumar"
#             - printenv
#           onCancel:
# #             - test "$ENV1" == "value1"
# #             - test "$SECURE_ENV" == "key"
#               - printenv
